#!/bin/sh
printf 'Enter password (not echoed): '
stty -echo
IFS= read -r pwd
stty echo

hash=$(printf %s "$pwd" | sha1sum | cut -c-40 | tr a-f A-F)
prefix=$(printf %s "$hash" | cut -c-5)
suffix=$(printf %s "$hash" | cut -c6-)

pwned=$(curl -sA 'https://github.com/knittl/pwnedpasswords.sh' "https://api.pwnedpasswords.com/range/$prefix" | grep "^$suffix:" | cut -d: -f2 | tr -cd 0-9)

if [ "$pwned" ]; then
	printf '\nPwned %s times\n' "$pwned"
else
	printf '\nNot pwned\n'
fi
